version: '3.7'

services:
    v2ray:
    container_name: v2ray
    hostname: v2ray
    image: v2ray/official:latest
    restart: always   
    ports:
      - '127.0.0.1:8888:8888'
    volumes:
      - '/etc/v2ray:/etc/v2ray'
    command: 'v2ray -config=/etc/v2ray/config.json'
